name: combine
channels:
- conda-forge
- defaults
dependencies:
- avro=1.8.2=0
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py35_0
- filelock=2.0.6=py35_0
- jansson=2.7=0
- ncurses=5.9=10
- openssl=1.0.2l=0
- pandas=0.20.3=py35_1
- pip=9.0.1=py35_0
- python=3.5.4=0
- python-avro=1.8.2=py35_0
- python-dateutil=2.6.1=py35_0
- pytz=2017.2=py35_0
- readline=6.2=0
- setuptools=36.6.0=py35_1
- six=1.11.0=py35_1
- snappy=1.1.7=1
- sqlite=3.13.0=1
- tk=8.5.19=2
- wheel=0.30.0=py_1
- xz=5.2.3=0
- zlib=1.2.11=0
- mkl=2017.0.3=0
- numpy=1.13.1=py35_0
- py=1.4.34=py35_0
- pytest=3.2.1=py35_0
- pip:
  - appnope==0.1.0
  - avro-python3==1.8.2
  - backports.shutil-get-terminal-size==1.0.0
  - chardet==3.0.4
  - cloudpickle==0.4.0
  - configparser==3.5.0
  - cookies==2.2.1
  - decorator==4.1.2
  - django==1.11.4
  - django-background-tasks==1.1.13
  - django-datatables-view==1.14.0
  - django-extensions==1.9.0
  - django-filter==1.1.0
  - django-pandas==0.4.5
  - django-tables2==1.13.0
  - elasticsearch==5.4.0
  - elasticsearch-dsl==5.3.0
  - enum34==1.1.6
  - future==0.16.0
  - futures==3.1.1
  - idna==2.6
  - ipython==6.1.0
  - ipython-genutils==0.2.0
  - jedi==0.10.2  
  - lxml==3.8.0
  - mysqlclient==1.3.10
  - openpyxl==2.4.9
  - pathlib2==2.3.0
  - pexpect==4.2.1
  - pickleshare==0.7.4
  - prompt-toolkit==1.0.15
  - ptyprocess==0.5.2
  - py4j==0.10.6
  - pydot==1.2.3
  - pygments==2.2.0
  - pyjxslt==0.7.0
  - pykerberos==1.1.14
  - pyparsing==2.2.0
  - requests==2.18.4
  - requests-kerberos==0.11.0
  - responses==0.8.1
  - scandir==1.5
  - Sickle==0.6.2
  - simplegeneric==0.8.1
  - Sphinx==1.7.2
  - sphinx-autobuild==0.7.1
  - sphinx-rtd-theme==0.3.0
  - sqlalchemy==1.1.13
  - traitlets==4.3.2
  - urllib3==1.22
  - wcwidth==0.1.7
  - xmltodict==0.11.0
prefix: /opt/miniconda/envs/combine

